### PR TITLE
Upgrade plugin for compatibility with guard 2.12.x

### PR DESCRIPTION
**Pull request by skrobul**
This set of changes makes the plugin compatible with newest version of Guard. There has been couple of [deprecated features](https://github.com/guard/guard/wiki/Upgrading-to-Guard-2.0) in new Guard as well as [couple accidental changes](https://github.com/guard/guard/issues/692) that caused backward incompatibility.

### CODE REVIEW

**Comment by skrobul** [comment]
@pmcjury any chance you could merge this?

**Comment by pmcjury** [comment]
Are they causing the other versions of ruby to fail? Need to fix the build or decide to deprecate support for those versions of ruby. Thoughts?

**Comment by bjmllr** [comment]
Guard has explicitly required ruby>=1.9.3 in `guard.gemspec` for some time (since 2.3.0), so I don't think it's possible to fix the build for some combinations of guard and ruby versions. I think the usual thing to do in this situation is to increment the major or minor version number and let people use `~>`.

**Comment by skrobul** [comment]
I'm with  @bjmlr on this one. There is no point in keeping support for old rubies. If someone needs to use `guard-remote-sync` with old ruby, he probably already has specific version pinned in Gemfile. As per comment above, Guard project [dropped](https://github.com/guard/guard/issues/424) 1.8 support more than a year ago - exactly 30 releases ago.

**Comment by pmcjury** [comment]
ok sounds good.

**Pull request merged**
